name: Registration
version: 1.1
main: me.millkun.registration.Registration
api-version: 1.12
commands:
  register:
    description: Register a new account
    aliases: [reg, регистрация, рег]
  login:
    description: Login to your account
    aliases: [log, логин, лог]
